# Generated by Django 3.2.10 on 2025-01-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDB',
        ),
    ]
